version: '2.1'
services:
  postgres:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur:edge
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY:
      RAILS_ENV: development
    depends_on:
      - postgres

  cli5:
    image: cyberark/conjur-cli:5
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber

  test-1.21:
    build:
      context: .
      args:
        FROM_IMAGE: "golang:1.21"
    ports:
      - 8080
    depends_on:
      - conjur
    volumes:
      - ./output:/conjur-api-go/output
    environment:
      CONJUR_DATA_KEY:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY:
      GO_VERSION:

  test-1.22:
    build:
      context: .
      args:
        FROM_IMAGE: "golang:1.22"
    ports:
      - 8080
    depends_on:
      - conjur
    volumes:
      - ./output:/conjur-api-go/output
    environment:
      CONJUR_DATA_KEY:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY:
      GO_VERSION:

  dev:
    build:
      context: .
      args:
        FROM_IMAGE: "golang:1.22"
    ports:
      - 8080
    depends_on:
      - conjur
    volumes:
      - .:/conjur-api-go
    environment:
      CONJUR_DATA_KEY:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY:
    entrypoint: sleep
    command: infinity
