[[constraint]]
  branch = "master"
  name = "github.com/bgentry/go-netrc"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
